[package]
name = "orgtag"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
id3 = "1.0.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "^1"
question = "0.2.2"
common-path = "1.0.0"
indicatif = "0.16.2"
regex = "1.5.4"
sanitize-filename = "0.3.0"
dirs = "4.0.0"
progress-streams = "1.1.0"
